name: krbn

targets:
  krbn:
    settings:
      CODE_SIGN_ENTITLEMENTS: ''
      CODE_SIGN_IDENTITY: '-'
      CODE_SIGN_STYLE: Manual
      HEADER_SEARCH_PATHS:
        # 保持不变，因为 include 目录在本地
        - include
        # 路径更新：从 ../../share 改为 deps/share
        - deps/share
      OTHER_SWIFT_FLAGS: '-warnings-as-errors'
      SWIFT_OBJC_BRIDGING_HEADER:
        # 路径更新：移除 ../../../
        - deps/vendor/vendor/include/pqrs/osx/frontmost_application_monitor/impl/Bridging-Header.h
      SYSTEM_HEADER_SEARCH_PATHS:
        # 路径更新：移除 ../../../
        - deps/vendor/Karabiner-DriverKit-VirtualHIDDevice/include
        - deps/vendor/vendor/include
    type: library.static
    platform: macOS
    deploymentTarget: 13.0
    sources:
      - path: src
        compilerFlags:
          - -Wall
          - -Werror
          - '-std=c++20'
      # 路径更新：移除 ../../../
      - path: deps/vendor/vendor/src/pqrs/osx/frontmost_application_monitor
